tensorflow:
  modeldir: "model" # working directory for tensorflow
  host: http://hostName:8888 
mongo:
  host: http://google.com:8888
  database: cerberServer
  MessagesTable: messages # todo
queue:
  host: amqp://login:password@host:5672/
  topic: picturesQueue