tensorflow:
  modeldir: "model" # working directory for tensorflow
  host: http://hostName.com:8888 
mongo:
  host: http://hostname.com:8888
  database: cerberServer
  MessagesTable: messages
queue:
  host: amqp://login:password@host:5672/
  topic: picturesQueue